In [2]:
! pip install scikit_learn
import pandas as pd

Requirement already satisfied: scikit_learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn) (3.6.0)

In [3]:
df= pd.read_csv("/content/homeprices_Multivariable.csv")

In [4]:
df.head()

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [7]:
df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].median())

In [8]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [9]:
X = df[['area','bedrooms','age']]
y = df['price']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred = model.predict(X_test)

In [14]:
model.coef_

array([  404.16666667,  9583.33333333, 31250.        ])

In [15]:
model.intercept_

np.float64(-1154583.333333333)

In [16]:
model.predict([[4500,2,4]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([808333.33333333])